# Importing necessary modules

In [1]:
import pandas as pd

# Reading the dataset

In [2]:
df = pd.read_csv("AB_NYC_2019.csv")

In [3]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

# Location - wise filtering

In [4]:
def location_filter(loc_name):
    return df.loc[df['neighbourhood_group'].str.contains(loc_name, case=False, regex=False)]

In [5]:
loc_df = location_filter(input("Enter required location: "))
loc_df

Enter required location: Brooklyn

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
6,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0
12,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,2019-06-24,1.34,3,314
15,6848,Only 2 stops to Manhattan studio,15991,Allen & Irina,Brooklyn,Williamsburg,40.70837,-73.95352,Entire home/apt,140,2,148,2019-06-29,1.20,1,46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48882,36482231,Bushwick _ Myrtle-Wyckoff,66058896,Luisa,Brooklyn,Bushwick,40.69652,-73.91079,Private room,40,20,0,NaN,NaN,1,31
48884,36482783,Brooklyn Oasis in the heart of Williamsburg,274307600,Jonathan,Brooklyn,Williamsburg,40.71790,-73.96238,Private room,190,7,0,NaN,NaN,1,341
48887,36483152,Garden Jewel Apartment in Williamsburg New York,208514239,Melki,Brooklyn,Williamsburg,40.71232,-73.94220,Entire home/apt,170,1,0,NaN,NaN,3,365
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36

# Room - wise filtering

In [6]:
def room_filter(room):
    return loc_df.loc[df['room_type'] == room.capitalize()]

In [7]:
room_df = room_filter(input("Enter required room type: "))
room_df

Enter required room type: Private room

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
6,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0
12,5803,"Lovely Room 1, Garden, Best Area, Legal rental",9744,Laurie,Brooklyn,South Slope,40.66829,-73.98779,Private room,89,4,167,2019-06-24,1.34,3,314
21,8024,CBG CtyBGd HelpsHaiti rm#1:1-4,22486,Lisel,Brooklyn,Park Slope,40.68069,-73.97706,Private room,130,2,130,2019-07-01,1.09,6,347
22,8025,CBG Helps Haiti Room#2.5,22486,Lisel,Brooklyn,Park Slope,40.67989,-73.97798,Private room,80,1,39,2019-01-01,0.37,6,364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48881,36481615,"Peaceful space in Greenpoint, BK",274298453,Adrien,Brooklyn,Greenpoint,40.72585,-73.94001,Private room,54,6,0,NaN,NaN,1,15
48882,36482231,Bushwick _ Myrtle-Wyckoff,66058896,Luisa,Brooklyn,Bushwick,40.69652,-73.91079,Private room,40,20,0,NaN,NaN,1,31
48884,36482783,Brooklyn Oasis in the heart of Williamsburg,274307600,Jonathan,Brooklyn,Williamsburg,40.71790,-73.96238,Private room,190,7,0,NaN,NaN,1,341
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36

# Price - wise filtering

In [8]:
def price(max_price, min_price):
    price_df = room_df.loc[(df['price'] <= max_price) & (df['price'] >= min_price)]
    return price_df.sort_values(by = 'price')

In [9]:
price_df = price(int(input("Enter maximum price: ")), int(input("Enter minimum price: ")))
price_df

Enter maximum price: 300
Enter minimum price: 250

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
163,40039,Luxurious Condo in DUBMO with View,171851,Henry,Brooklyn,DUMBO,40.70207,-73.98571,Private room,250,3,14,2011-04-25,0.13,1,189
25316,20243875,Bright 3 floors home in Bushwick with precious...,6760095,Maria Veronica,Brooklyn,Bushwick,40.70089,-73.92730,Private room,250,2,0,NaN,NaN,1,260
25831,20660511,The plaza suite in brooklyn. Bedstuy style,29093058,Joann,Brooklyn,Bedford-Stuyvesant,40.69574,-73.93975,Private room,250,2,0,NaN,NaN,2,173
45989,35025129,Greenpoint Williamsburg only min to the city,312722,Kristian & Di,Brooklyn,Greenpoint,40.72572,-73.95664,Private room,250,29,0,NaN,NaN,4,157
27948,21863385,tranquil house,88852894,Nando,Brooklyn,Sheepshead Bay,40.59664,-73.95301,Private room,250,2,0,NaN,NaN,1,178
28977,22308705,"Private, Roomy, Convenient Williamsburg Hotspot",23165019,Alex,Brooklyn,Williamsburg,40.70689,-73.95060,Private room,250,1,8,2018-06-13,0.43,1,0
30508,23610982,Brooklyn Duplex w manhattan flare,91511951,Libertad,Brooklyn,Prospect Heights,40.68020,-73.96504,Private room,250,3,3,2018-06-13,0.21,1,0
22673,18355480,Williamsburg Plant Filled Sunny Apartment :D,16718650,Joseph,Brooklyn,Williamsburg,40.71099,-73.95825,Private room,250,1,0,NaN,NaN,1,0
35283,27984123,The Space in Brooklyn,57484031,Frederick,Brooklyn,Crown Heights,40.66472,-73.92871,Private room,250,1,0,NaN,NaN,1,0
37156,29531069,greenpoint williamsburg huge studio room /,150316502,Francisca,Brooklyn,Greenpoint,40.72674,-73.95495,Private room,250,5,0,NaN,NaN,1,154
40469,31369708,ROOMS ONE and TWO,226036723,Ravita,Brooklyn,Cypress Hills,40.68537,-73.87442,Private room,250,3,0,NaN,NaN,3,364
40936,31837233,Beautiful room in Bushwick,11672284,Hea,Brooklyn,Bushwick,40.70526,-73.92446,Private room,250,2,0,NaN,NaN,2,97
45179,34578233,Peaceful Apartment in Lefferts Gardens,158123420,Jane,Brooklyn,Prospect-Lefferts Gardens,40.65596,-73.95679,Private room,250,5,0,NaN,NaN,1,23
45376,34710645,Furnished Room available in New Building with AC,82187372,David,Brooklyn,Williamsburg,40.71469,-73.95401,Private room,250,10,0,NaN,NaN,1,78
45484,34784681,Brooklyn Home,262287464,Daniel,Brooklyn,Boerum Hill,40.68713,-73.98592,Private room,250,1,1,2019-05-20,0.59,1,365
35294,27989719,Private Room in Prospect Place,38886949,Nishant,Brooklyn,Prospect Heights,40.67893,-73.97113,Private room,250,16,0,NaN,NaN,2,89
22106,17780857,"SUPER HIGH END condo, roof deck, Ditmas Park B...",121429669,Elizanda,Brooklyn,Kensington,40.63052,-73.97161,Private room,250,2,0,NaN,NaN,1,365
27582,21698837,Dope ass apt,149576949,McKayla,Brooklyn,Bedford-Stuyvesant,40.68519,-73.92868,Private room,250,1,0,NaN,NaN,1,0
47929,35992337,Private 1 bedroom studio bed and breakfast,145140746,Regina,Brooklyn,Bedford-Stuyvesant,40.68735,-73.92770,Private room,250,2,0,NaN,NaN,1,350
20122,16119541,Huge guest suite with private bath and kitchen.,700224,Shane & Nicole,Brooklyn,Boerum Hill,40.68424,-73.98545,Private room,250,5,0,NaN,NaN,4,50
5117,3683236,Peaceful 2BR inside a brownstone,378737,Parris,Brooklyn,Bedford-Stuyvesant,40.68908,-73.92893,Private room,250,2,0,NaN,NaN,1,365
1496,673760,Sunrise Room in Spacious Duplex,2219255,Natalie,Brooklyn,Canarsie,40.62764,-73.90086,Private room,250,2,70,2018-10-10,0.85,3,0
15668,12652964,Cozy 1 bedroom in 2BD apt. in Bed-Stuy. Long t...,13996246,JaNae,Brooklyn,Bedford-Stuyvesant,40.68198,-73.95347,Private room,250,60,2,2016-06-08,0.05,1,0
14422,11305912,_Special Offers: Guest Assistance,344035,Brooklyn& Breakfast -Len-,Brooklyn,Prospect Heights,40.67771,-73.96979,Private room,250,1,25,2019-05-01,0.63,13,0
10885,8398120,one bedroom apt 1000sqf,17871237,Mandy,Brooklyn,Williamsburg,40.71599,-73.95514,Private room,250,5,0,NaN,NaN,1,0
22001,17697886,Park Slope Gem,120577640,David,Brooklyn,Park Slope,40.66926,-73.97862,Private room,250,1,0,NaN,NaN,1,89
4773,3378576,Private room in Williamsburg Apt,6273146,Jon,Brooklyn,Williamsburg,40.70935,-73.94614,Private room,250,1,0,NaN,NaN,1,0
7797,5925343,The Notorious B.N.B. { The William Henry },1177497,Jessica,Brooklyn,Clinton Hill,40.68963,-73.96713,Private room,259,1,94,2019-06-26,1.85,11,365
35683,28329076,2BR Williamsburg home w/ PATIO! Baby Gear! L t...,106950680,Elmie,Brooklyn,Williamsburg,40.71392,-73.94034,Private room,274,3,3,2019-06-17,0.31,1,0
2655,1407364,BROOKLYN'S FAVORITE BROWNSTONE in HIPSTER BED-...,7591257,Ruty,Brooklyn,Bedford-Stuyvesant,40.68444,-73.94201,Private room,275,3,20,2019-04-28,0.34,1,257
28782,22231328,Spacious Brooklyn loft in Clinton Hill,4642506,Devin,Brooklyn,Bedford-Stuyvesant,40.69216,-73.96011,Private room,275,2,17,2019-06-25,0.92,1,72
640,242532,The Notorious B.N.B. { The Swoon },1177497,Jessica,Brooklyn,Clinton Hill,40.68930,-73.96602,Private room,279,1,120,2019-06-19,1.28,11,362
38929,30441793,Cozy Brooklyn Room,200055931,Jessica,Brooklyn,Red Hook,40.67441,-74.01278,Private room,280,1,0,NaN,NaN,1,90
34169,27096053,hip cool House,203650630,Ardinia,Brooklyn,Coney Island,40.57210,-73.99712,Private room,290,1,1,2019-05-31,0.75,1,364
39123,30531953,SUPERIOR KING ROOM -PRIME WILLIAMSBURG,198861577,Novo,Brooklyn,Williamsburg,40.72132,-73.95463,Private room,295,1,2,2019-04-04,0.60,5,90
681,253842,1 BR w/ Terrace @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73714,-73.95296,Private room,299,3,6,2018-04-19,0.10,28,60
37545,29792553,Stunningly Bright Room with NYC Skyline Views,10928484,Stan,Brooklyn,Williamsburg,40.71843,-73.94199,Private room,299,4,0,NaN,NaN,1,35
21213,16841844,South Williamsburg bedroom with big bay windows,28758646,Alex,Brooklyn,Williamsburg,40.70942,-73.96331,Private room,300,3,4,2017-05-20,0.15,1,0
31198,24229031,3 QUEEN size lofts in Williamsburg/grrenpoint!!!,182363374,Jimmy,Brooklyn,Greenpoint,40.72552,-73.95647,Private room,300,1,8,2018-11-11,0.53,7,14
27876,21829161,Brooklyn Studio,35404558,Brian,Brooklyn,Bedford-Stuyvesant,40.68476,-73.95801,Private room,300,1,4,2018-06-23,0.20,1,0
17541,13795756,"Lovely S.Slope 3BR in 4BR 1300 sf dplx,deck&bi...",514261,Vanessa,Brooklyn,South Slope,40.66537,-73.98784,Private room,300,2,2,2016-09-06,0.06,3,0
19713,15785785,Harrigan Luxury Townhouse Suite,102108786,Marie,Brooklyn,East New York,40.67240,-73.88839,Private room,300,3,8,2019-05-06,0.26,2,80
31343,24355169,HUGE Modern Room/office/studio w Private Entrance,43037915,Edward,Brooklyn,Crown Heights,40.66371,-73.95698,Private room,300,2,0,NaN,NaN,1,0
8440,6479956,Spacious private room,13356805,Sophie,Brooklyn,Park Slope,40.66753,-73.97747,Private room,300,1,0,NaN,NaN,1,0

# Sorting existing dataset by number of reviews
(Highest to Lowest)

In [10]:
def review_filter():
    sort_by_review_df = price_df.sort_values(by = 'number_of_reviews', ascending = False)
    return sort_by_review_df

In [11]:
review_filter()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
640,242532,The Notorious B.N.B. { The Swoon },1177497,Jessica,Brooklyn,Clinton Hill,40.68930,-73.96602,Private room,279,1,120,2019-06-19,1.28,11,362
7797,5925343,The Notorious B.N.B. { The William Henry },1177497,Jessica,Brooklyn,Clinton Hill,40.68963,-73.96713,Private room,259,1,94,2019-06-26,1.85,11,365
1496,673760,Sunrise Room in Spacious Duplex,2219255,Natalie,Brooklyn,Canarsie,40.62764,-73.90086,Private room,250,2,70,2018-10-10,0.85,3,0
14422,11305912,_Special Offers: Guest Assistance,344035,Brooklyn& Breakfast -Len-,Brooklyn,Prospect Heights,40.67771,-73.96979,Private room,250,1,25,2019-05-01,0.63,13,0
2655,1407364,BROOKLYN'S FAVORITE BROWNSTONE in HIPSTER BED-...,7591257,Ruty,Brooklyn,Bedford-Stuyvesant,40.68444,-73.94201,Private room,275,3,20,2019-04-28,0.34,1,257
28782,22231328,Spacious Brooklyn loft in Clinton Hill,4642506,Devin,Brooklyn,Bedford-Stuyvesant,40.69216,-73.96011,Private room,275,2,17,2019-06-25,0.92,1,72
163,40039,Luxurious Condo in DUBMO with View,171851,Henry,Brooklyn,DUMBO,40.70207,-73.98571,Private room,250,3,14,2011-04-25,0.13,1,189
31198,24229031,3 QUEEN size lofts in Williamsburg/grrenpoint!!!,182363374,Jimmy,Brooklyn,Greenpoint,40.72552,-73.95647,Private room,300,1,8,2018-11-11,0.53,7,14
28977,22308705,"Private, Roomy, Convenient Williamsburg Hotspot",23165019,Alex,Brooklyn,Williamsburg,40.70689,-73.95060,Private room,250,1,8,2018-06-13,0.43,1,0
19713,15785785,Harrigan Luxury Townhouse Suite,102108786,Marie,Brooklyn,East New York,40.67240,-73.88839,Private room,300,3,8,2019-05-06,0.26,2,80
681,253842,1 BR w/ Terrace @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,40.73714,-73.95296,Private room,299,3,6,2018-04-19,0.10,28,60
27876,21829161,Brooklyn Studio,35404558,Brian,Brooklyn,Bedford-Stuyvesant,40.68476,-73.95801,Private room,300,1,4,2018-06-23,0.20,1,0
21213,16841844,South Williamsburg bedroom with big bay windows,28758646,Alex,Brooklyn,Williamsburg,40.70942,-73.96331,Private room,300,3,4,2017-05-20,0.15,1,0
30508,23610982,Brooklyn Duplex w manhattan flare,91511951,Libertad,Brooklyn,Prospect Heights,40.68020,-73.96504,Private room,250,3,3,2018-06-13,0.21,1,0
35683,28329076,2BR Williamsburg home w/ PATIO! Baby Gear! L t...,106950680,Elmie,Brooklyn,Williamsburg,40.71392,-73.94034,Private room,274,3,3,2019-06-17,0.31,1,0
39123,30531953,SUPERIOR KING ROOM -PRIME WILLIAMSBURG,198861577,Novo,Brooklyn,Williamsburg,40.72132,-73.95463,Private room,295,1,2,2019-04-04,0.60,5,90
17541,13795756,"Lovely S.Slope 3BR in 4BR 1300 sf dplx,deck&bi...",514261,Vanessa,Brooklyn,South Slope,40.66537,-73.98784,Private room,300,2,2,2016-09-06,0.06,3,0
15668,12652964,Cozy 1 bedroom in 2BD apt. in Bed-Stuy. Long t...,13996246,JaNae,Brooklyn,Bedford-Stuyvesant,40.68198,-73.95347,Private room,250,60,2,2016-06-08,0.05,1,0
45484,34784681,Brooklyn Home,262287464,Daniel,Brooklyn,Boerum Hill,40.68713,-73.98592,Private room,250,1,1,2019-05-20,0.59,1,365
34169,27096053,hip cool House,203650630,Ardinia,Brooklyn,Coney Island,40.57210,-73.99712,Private room,290,1,1,2019-05-31,0.75,1,364
47929,35992337,Private 1 bedroom studio bed and breakfast,145140746,Regina,Brooklyn,Bedford-Stuyvesant,40.68735,-73.92770,Private room,250,2,0,NaN,NaN,1,350
38929,30441793,Cozy Brooklyn Room,200055931,Jessica,Brooklyn,Red Hook,40.67441,-74.01278,Private room,280,1,0,NaN,NaN,1,90
31343,24355169,HUGE Modern Room/office/studio w Private Entrance,43037915,Edward,Brooklyn,Crown Heights,40.66371,-73.95698,Private room,300,2,0,NaN,NaN,1,0
25831,20660511,The plaza suite in brooklyn. Bedstuy style,29093058,Joann,Brooklyn,Bedford-Stuyvesant,40.69574,-73.93975,Private room,250,2,0,NaN,NaN,2,173
45989,35025129,Greenpoint Williamsburg only min to the city,312722,Kristian & Di,Brooklyn,Greenpoint,40.72572,-73.95664,Private room,250,29,0,NaN,NaN,4,157
27948,21863385,tranquil house,88852894,Nando,Brooklyn,Sheepshead Bay,40.59664,-73.95301,Private room,250,2,0,NaN,NaN,1,178
22673,18355480,Williamsburg Plant Filled Sunny Apartment :D,16718650,Joseph,Brooklyn,Williamsburg,40.71099,-73.95825,Private room,250,1,0,NaN,NaN,1,0
35283,27984123,The Space in Brooklyn,57484031,Frederick,Brooklyn,Crown Heights,40.66472,-73.92871,Private room,250,1,0,NaN,NaN,1,0
37545,29792553,Stunningly Bright Room with NYC Skyline Views,10928484,Stan,Brooklyn,Williamsburg,40.71843,-73.94199,Private room,299,4,0,NaN,NaN,1,35
37156,29531069,greenpoint williamsburg huge studio room /,150316502,Francisca,Brooklyn,Greenpoint,40.72674,-73.95495,Private room,250,5,0,NaN,NaN,1,154
40469,31369708,ROOMS ONE and TWO,226036723,Ravita,Brooklyn,Cypress Hills,40.68537,-73.87442,Private room,250,3,0,NaN,NaN,3,364
40936,31837233,Beautiful room in Bushwick,11672284,Hea,Brooklyn,Bushwick,40.70526,-73.92446,Private room,250,2,0,NaN,NaN,2,97
20122,16119541,Huge guest suite with private bath and kitchen.,700224,Shane & Nicole,Brooklyn,Boerum Hill,40.68424,-73.98545,Private room,250,5,0,NaN,NaN,4,50
45179,34578233,Peaceful Apartment in Lefferts Gardens,158123420,Jane,Brooklyn,Prospect-Lefferts Gardens,40.65596,-73.95679,Private room,250,5,0,NaN,NaN,1,23
45376,34710645,Furnished Room available in New Building with AC,82187372,David,Brooklyn,Williamsburg,40.71469,-73.95401,Private room,250,10,0,NaN,NaN,1,78
35294,27989719,Private Room in Prospect Place,38886949,Nishant,Brooklyn,Prospect Heights,40.67893,-73.97113,Private room,250,16,0,NaN,NaN,2,89
4773,3378576,Private room in Williamsburg Apt,6273146,Jon,Brooklyn,Williamsburg,40.70935,-73.94614,Private room,250,1,0,NaN,NaN,1,0
22001,17697886,Park Slope Gem,120577640,David,Brooklyn,Park Slope,40.66926,-73.97862,Private room,250,1,0,NaN,NaN,1,89
10885,8398120,one bedroom apt 1000sqf,17871237,Mandy,Brooklyn,Williamsburg,40.71599,-73.95514,Private room,250,5,0,NaN,NaN,1,0
22106,17780857,"SUPER HIGH END condo, roof deck, Ditmas Park B...",121429669,Elizanda,Brooklyn,Kensington,40.63052,-73.97161,Private room,250,2,0,NaN,NaN,1,365
25316,20243875,Bright 3 floors home in Bushwick with precious...,6760095,Maria Veronica,Brooklyn,Bushwick,40.70089,-73.92730,Private room,250,2,0,NaN,NaN,1,260
27582,21698837,Dope ass apt,149576949,McKayla,Brooklyn,Bedford-Stuyvesant,40.68519,-73.92868,Private room,250,1,0,NaN,NaN,1,0
5117,3683236,Peaceful 2BR inside a brownstone,378737,Parris,Brooklyn,Bedford-Stuyvesant,40.68908,-73.92893,Private room,250,2,0,NaN,NaN,1,365
8440,6479956,Spacious private room,13356805,Sophie,Brooklyn,Park Slope,40.66753,-73.97747,Private room,300,1,0,NaN,NaN,1,0